name: Check Version Number
on:
  pull_request:
    branches:
      - master

jobs:
  check-diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # - uses: pooyad359/version-check-action@v0.0.2
