name: Check Version Number v2
on:
  pull_request:
    types: [ready_for_review]
    branches:
      - master

jobs:
  check-diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: CheckVersion
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          CURRENT_VERSION=`cat pyproject.toml | sed -rn 's/version = "(.*)"/\1/p'`
          PREV_VERSION=`git show origin/$GITHUB_BASE_REF:pyproject.toml | sed -rn 's/version = "(.*)"/\1/p'`
          echo "Current Version:    ${CURRENT_VERSION}"
          echo "Previous Version:   ${PREV_VERSION}"
          python version_check.py $PREV_VERSION $CURRENT_VERSION
