name: Check Version Number v2
on:
  pull_request:
    branches:
      - master

jobs:
  check-diff:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: terminal
        run: |
          CURRENT_VERSION=`cat pyproject.toml | sed -rn 's/version = "(.*)"/\1/p'`
          PREV_VERSION=`git show $GITHUB_BASE_REF:pyproject.toml | sed -rn 's/version = "(.*)"/\1/p'`
          echo "version = ${CURRENT_VERSION}"
          echo "1: ${{github.ref_name}}"
          echo "2: $INPUT_DEFAULT_BRANCH "
          echo "3: $GITHUB_BASE_REF"
          echo "4: $GITHUB_REF"
          echo "5: $GITHUB_REF_NAME"

